// ============================================
// Second Brain AI — Utility Engine
// ============================================

function showToast(message, type = 'info') {
  const container = document.getElementById('toast-container');
  if (!container) return;
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  const icon = type === 'success' ? '✓' : type === 'error' ? '✕' : 'ℹ';
  const iconEl = document.createElement('div');
  iconEl.className = 'toast-icon';
  iconEl.textContent = icon;
  const messageEl = document.createElement('div');
  messageEl.className = 'toast-message';
  messageEl.textContent = String(message || '');
  toast.append(iconEl, messageEl);
  container.appendChild(toast);
  setTimeout(() => toast.classList.add('show'), 10);
  setTimeout(() => {
    toast.classList.remove('show');
    setTimeout(() => toast.remove(), 300);
  }, 3200);
}

function escapeHTML(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatMarkdownText(mdText) {
  if (!mdText) return '';

  // AI output is untrusted content. Escape it before adding only the HTML
  // elements generated by this formatter. This prevents model-output XSS.
  let html = escapeHTML(mdText);

  html = html.replace(/```([a-zA-Z0-9_+-]*)\n([\s\S]*?)```/g, (match, lang, code) => {
    const cleanLang = (lang || 'text').trim() || 'text';
    const canvasBtn = /html|xml|svg|js|javascript|css|jsx|tsx|web/i.test(cleanLang)
      ? '<button class="code-copy-btn canvas-run-btn" onclick="window.runInCanvasFromBlock(this)" type="button">🚀 Run in Canvas</button>'
      : '';
    return `<div class="code-block-wrapper"><div class="code-block-header"><span class="code-lang-label">${cleanLang}</span><div class="code-header-actions">${canvasBtn}<button class="code-copy-btn" onclick="window.copyCodeFromBlock(this)" type="button">📋 Copy Code</button></div></div><pre class="code-block-content"><code class="language-${cleanLang}">${code.trim()}</code></pre></div>`;
  });

  html = html.replace(/\[cite:\s*([^\]]+)\]/g, '<span class="inline-citation-chip">📄 $1</span>');
  html = html.replace(/\[([^\]]{1,120})\]/g, (match, label) => {
    // Only style citation-like bracket labels; do not turn arbitrary text into HTML.
    if (/^(source|citation|ref|note|paper|doc)\b/i.test(label.trim())) {
      return `<span class="inline-citation-chip">📄 ${label}</span>`;
    }
    return match;
  });
  html = html.replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>');
  html = html.replace(/^#### (.*$)/gim, '<h4 class="md-h4">$1</h4>');
  html = html.replace(/^### (.*$)/gim, '<h3 class="md-h3">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="md-h2">$1</h2>');
  html = html.replace(/📅\s*\*\*([^*]+)\*\*/g, '<div class="date-callout-card"><span class="date-icon">📅</span><span>$1</span></div>');
  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  html = html.replace(/^\s*[-*] (.*$)/gim, '<li class="md-li">$1</li>');
  html = html.replace(/(<li class="md-li">.*<\/li>\n?)+/g, '<ul class="md-ul">$&</ul>');
  html = html.replace(/\n\n/g, '<br><br>');
  html = html.replace(/\n/g, '<br>');
  return html;
}

function copyCodeFromBlock(btnEl) {
  const wrapper = btnEl && btnEl.closest('.code-block-wrapper');
  if (!wrapper) return;
  const codeEl = wrapper.querySelector('code');
  if (codeEl && navigator.clipboard) {
    navigator.clipboard.writeText(codeEl.textContent).then(() => {
      btnEl.textContent = '✓ Copied!';
      setTimeout(() => { btnEl.textContent = '📋 Copy Code'; }, 2000);
    }).catch(() => {});
  }
}

function runInCanvasFromBlock(btnEl) {
  const wrapper = btnEl && btnEl.closest('.code-block-wrapper');
  if (!wrapper) return;
  const codeEl = wrapper.querySelector('code');
  if (codeEl && typeof window.runInCanvas === 'function') window.runInCanvas(codeEl.textContent);
}

window.showToast = showToast;
window.escapeHTML = escapeHTML;
window.formatMarkdownText = formatMarkdownText;
window.copyCodeFromBlock = copyCodeFromBlock;
window.runInCanvasFromBlock = runInCanvasFromBlock;

// ------------------------------------------------------------
// Production chat compatibility bridge
// ------------------------------------------------------------
// The production controller is loaded separately. If a user submits before
// that controller finishes loading, preserve the prompt and retry instead of
// clearing the composer and silently dropping the first message.
(function installProductionChatCompatibilityBridge() {
  const PRODUCTION_CHAT_SRC = 'js/production-chat.js?v=3.1';

  function ensureProductionChatLoaded(prompt) {
    const existingHandler = window.handleRAGQuery;
    if (typeof existingHandler === 'function') {
      existingHandler(prompt);
      return;
    }

    let script = document.querySelector('script[data-juno-production-chat]');
    if (!script) {
      script = document.createElement('script');
      script.src = PRODUCTION_CHAT_SRC;
      script.dataset.junoProductionChat = 'true';
      script.async = true;
      script.onload = () => {
        if (typeof window.handleRAGQuery === 'function') {
          window.handleRAGQuery(prompt);
        } else {
          showToast('Juno chat controller loaded, but is not ready yet.', 'warning');
        }
      };
      script.onerror = () => {
        showToast('Juno chat controller could not be loaded. Please refresh once.', 'error');
      };
      document.body.appendChild(script);
      return;
    }

    // A controller script is already loading. Poll briefly so the current
    // prompt is delivered once the global handler is installed.
    let attempts = 0;
    const retry = () => {
      if (typeof window.handleRAGQuery === 'function') {
        window.handleRAGQuery(prompt);
        return;
      }
      attempts += 1;
      if (attempts < 40) {
        setTimeout(retry, 50);
      } else {
        showToast('Juno is taking too long to initialize. Please refresh once.', 'warning');
      }
    };
    retry();
  }

  window.submitRAGQuery = function (event) {
    event?.preventDefault?.();
    event?.stopPropagation?.();

    const input = document.getElementById('rag-query-input');
    const prompt = String(input?.value || '').trim();
    if (!prompt) return false;

    // Only clear after a real production handler exists. This prevents the
    // exact failure mode where the first typed message disappears with no reply.
    if (typeof window.handleRAGQuery === 'function') {
      if (input) input.value = '';
      window.handleRAGQuery(prompt);
      return false;
    }

    showToast('Juno is loading — sending your message as soon as chat is ready.', 'info');
    ensureProductionChatLoaded(prompt);
    return false;
  };
})();
