// ============================================
// Second Brain AI — Utility Engine
// ============================================

function showToast(message, type = 'info') {
  const container = document.getElementById('toast-container');
  if (!container) return;
  const toast = document.createElement('div');
  toast.className = `toast toast-${type}`;
  const icon = type === 'success' ? '✓' : type === 'error' ? '✕' : 'ℹ';
  const iconEl = document.createElement('div');
  iconEl.className = 'toast-icon';
  iconEl.textContent = icon;
  const messageEl = document.createElement('div');
  messageEl.className = 'toast-message';
  messageEl.textContent = String(message || '');
  toast.append(iconEl, messageEl);
  container.appendChild(toast);
  setTimeout(() => toast.classList.add('show'), 10);
  setTimeout(() => {
    toast.classList.remove('show');
    setTimeout(() => toast.remove(), 300);
  }, 3200);
}

function escapeHTML(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatMarkdownText(mdText) {
  if (!mdText) return '';

  // AI output is untrusted content. Escape it before adding only the HTML
  // elements generated by this formatter. This prevents model-output XSS.
  let html = escapeHTML(mdText);

  html = html.replace(/```([a-zA-Z0-9_+-]*)\n([\s\S]*?)```/g, (match, lang, code) => {
    const cleanLang = (lang || 'text').trim() || 'text';
    const canvasBtn = /html|xml|svg|js|javascript|css|jsx|tsx|web/i.test(cleanLang)
      ? '<button class="code-copy-btn canvas-run-btn" onclick="window.runInCanvasFromBlock(this)" type="button">🚀 Run in Canvas</button>'
      : '';
    return `<div class="code-block-wrapper"><div class="code-block-header"><span class="code-lang-label">${cleanLang}</span><div class="code-header-actions">${canvasBtn}<button class="code-copy-btn" onclick="window.copyCodeFromBlock(this)" type="button">📋 Copy Code</button></div></div><pre class="code-block-content"><code class="language-${cleanLang}">${code.trim()}</code></pre></div>`;
  });

  html = html.replace(/\[cite:\s*([^\]]+)\]/g, '<span class="inline-citation-chip">📄 $1</span>');
  html = html.replace(/\[([^\]]{1,120})\]/g, (match, label) => {
    // Only style citation-like bracket labels; do not turn arbitrary text into HTML.
    if (/^(source|citation|ref|note|paper|doc)\b/i.test(label.trim())) {
      return `<span class="inline-citation-chip">📄 ${label}</span>`;
    }
    return match;
  });
  html = html.replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>');
  html = html.replace(/^#### (.*$)/gim, '<h4 class="md-h4">$1</h4>');
  html = html.replace(/^### (.*$)/gim, '<h3 class="md-h3">$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2 class="md-h2">$1</h2>');
  html = html.replace(/📅\s*\*\*([^*]+)\*\*/g, '<div class="date-callout-card"><span class="date-icon">📅</span><span>$1</span></div>');
  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  html = html.replace(/^\s*[-*] (.*$)/gim, '<li class="md-li">$1</li>');
  html = html.replace(/(<li class="md-li">.*<\/li>\n?)+/g, '<ul class="md-ul">$&</ul>');
  html = html.replace(/\n\n/g, '<br><br>');
  html = html.replace(/\n/g, '<br>');
  return html;
}

function copyCodeFromBlock(btnEl) {
  const wrapper = btnEl && btnEl.closest('.code-block-wrapper');
  if (!wrapper) return;
  const codeEl = wrapper.querySelector('code');
  if (codeEl && navigator.clipboard) {
    navigator.clipboard.writeText(codeEl.textContent).then(() => {
      btnEl.textContent = '✓ Copied!';
      setTimeout(() => { btnEl.textContent = '📋 Copy Code'; }, 2000);
    }).catch(() => {});
  }
}

function runInCanvasFromBlock(btnEl) {
  const wrapper = btnEl && btnEl.closest('.code-block-wrapper');
  if (!wrapper) return;
  const codeEl = wrapper.querySelector('code');
  if (codeEl && typeof window.runInCanvas === 'function') window.runInCanvas(codeEl.textContent);
}

window.showToast = showToast;
window.escapeHTML = escapeHTML;
window.formatMarkdownText = formatMarkdownText;
window.copyCodeFromBlock = copyCodeFromBlock;
window.runInCanvasFromBlock = runInCanvasFromBlock;

// ------------------------------------------------------------
// Production chat bootstrap / single-submit guard
// ------------------------------------------------------------
// The chat controller used to be loaded only after the first message. That
// created a race: Enter could clear the textarea before the controller existed.
// This bootstrap loads the controller early and owns the first Enter/submit
// event at document-capture level, so inline handlers and late listeners cannot
// swallow the user's first message.
(function installProductionChatBootstrap() {
  const PRODUCTION_CHAT_SRC = 'js/production-chat.js?v=4.0';
  let controllerPromise = null;
  let queuedPrompt = null;
  let dispatching = false;

  function loadProductionChat() {
    if (typeof window.handleRAGQuery === 'function') return Promise.resolve(true);
    if (controllerPromise) return controllerPromise;

    controllerPromise = new Promise((resolve) => {
      const existing = document.querySelector('script[data-juno-production-chat]');
      if (existing) {
        existing.addEventListener('load', () => resolve(typeof window.handleRAGQuery === 'function'), { once: true });
        existing.addEventListener('error', () => resolve(false), { once: true });
        return;
      }

      const script = document.createElement('script');
      script.src = PRODUCTION_CHAT_SRC;
      script.dataset.junoProductionChat = 'true';
      script.async = true;
      script.onload = () => resolve(typeof window.handleRAGQuery === 'function');
      script.onerror = () => resolve(false);
      (document.head || document.documentElement).appendChild(script);
    });

    return controllerPromise;
  }

  function clearInput(input) {
    if (!input) return;
    input.value = '';
    input.style.height = 'auto';
  }

  async function dispatchPrompt(input, event) {
    if (dispatching) return true;
    const prompt = String(input?.value || '').trim();
    if (!prompt) return false;

    // Stop every other submit/keydown path. The original message remains in
    // the textarea until the real production controller accepts it.
    event?.preventDefault?.();
    event?.stopPropagation?.();
    event?.stopImmediatePropagation?.();

    dispatching = true;
    try {
      if (typeof window.handleRAGQuery !== 'function') {
        queuedPrompt = prompt;
        if (typeof showToast === 'function') {
          showToast('Juno is starting… your message is being kept safely.', 'info');
        }
        const ready = await loadProductionChat();
        if (!ready || typeof window.handleRAGQuery !== 'function') {
          if (typeof showToast === 'function') {
            showToast('Juno could not start. Your message is still in the composer.', 'error');
          }
          return false;
        }
      }

      const handler = window.handleRAGQuery;
      const accepted = handler(prompt);
      // handleRAGQuery is async, so reaching this point means it has already
      // synchronously accepted the prompt and rendered the user/thinking state.
      clearInput(input);
      queuedPrompt = null;
      return accepted;
    } catch (error) {
      console.error('[Juno submit guard]', error);
      if (typeof showToast === 'function') showToast('Message was not sent. It remains in the composer.', 'error');
      return false;
    } finally {
      dispatching = false;
    }
  }

  // Capture Enter before the textarea's inline onkeydown and before any late
  // module can attach another handler.
  document.addEventListener('keydown', (event) => {
    if (event.key !== 'Enter' || event.shiftKey) return;
    const target = event.target;
    if (!target || target.id !== 'rag-query-input') return;
    void dispatchPrompt(target, event);
  }, true);

  // Also cover clicking the Send button / form submission.
  document.addEventListener('submit', (event) => {
    const form = event.target;
    if (!form || form.id !== 'rag-query-form') return;
    const input = document.getElementById('rag-query-input');
    void dispatchPrompt(input, event);
  }, true);

  // Preload the controller as early as possible. The guarded event path above
  // remains the fallback if the network is still loading when the user presses Enter.
  loadProductionChat();

  // Keep the public function for existing UI code, but route it through the
  // same safe dispatcher rather than clearing the composer first.
  window.submitRAGQuery = function (event) {
    const input = document.getElementById('rag-query-input');
    return dispatchPrompt(input, event);
  };

  window.junoChatReady = loadProductionChat;
  window.junoQueuedPrompt = () => queuedPrompt;
})();
